name: "Submit Job to AWS Batch"
inputs:
  job-type:
    required: true
  job-name:
    required: true
  work-dir:
    required: false
    default: .
  command:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::369469875935:role/AutoGluonCiRole
        role-duration-seconds: 14400
        aws-region: us-east-1
    - name: Install dependencies
      shell: bash
      run: |
        pip install boto3
    - name: Check for Actor Permission
      id: check
      continue-on-error: true
      uses: prince-chrismc/check-actor-permissions-action@v2
      with:
        github_token: ${{ github.token }}
        permission: write
    - name: Submit Job(For Push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "Start submitting job"
        python ./CI/batch/submit-job.py --job-type ${{ inputs.job-type }}-PUSH \
                                        --name ${{ inputs.job-name }}-'${{ github.ref }}' \
                                        --source-ref '${{ github.ref }}' \
                                        --work-dir ${{ inputs.work-dir }} \
                                        --remote https://github.com/'${{ github.repository }}' \
                                        --command "${{ inputs.command }}" \
                                        --safe-to-use-script \
                                        --wait
    - name: Submit Job(For Pull Request Safe Scripts)
      if: ${{ github.event_name == 'pull_request_target' && steps.check.outputs.permitted == 'true' }}
      shell: bash
      run: |
        echo "Start submitting job"
        python ./CI/batch/submit-job.py --job-type ${{ inputs.job-type }} \
                                        --name ${{ inputs.job-name }}-PR#'${{ github.event.number }}' \
                                        --source-ref '${{ github.event.pull_request.head.sha }}' \
                                        --work-dir ${{ inputs.work-dir }} \
                                        --remote https://github.com/'${{ github.event.pull_request.head.repo.full_name }}' \
                                        --command "${{ inputs.command }}" \
                                        --safe-to-use-script \
                                        --wait
    - name: Submit Job(For Pull Request Not Safe Scripts)
      if: ${{ github.event_name == 'pull_request_target' && steps.check.outputs.permitted != 'true' }}
      shell: bash
      run: |
        echo "Start submitting job"
        python ./CI/batch/submit-job.py --job-type ${{ inputs.job-type }} \
                                        --name ${{ inputs.job-name }}-PR#'${{ github.event.number }}' \
                                        --source-ref '${{ github.event.pull_request.head.sha }}' \
                                        --work-dir ${{ inputs.work-dir }} \
                                        --remote https://github.com/'${{ github.event.pull_request.head.repo.full_name }}' \
                                        --command "${{ inputs.command }}" \
                                        --wait
