!!python/object:autogluon.tabular.models.tabpfnmix._internal.config.config_run.ConfigRun
hyperparams:
  attn_dropout: 0.0
  dim: 512
  early_stopping_patience: 40  # FIXME: Reduce?
  linear_attention: true
  lr: 1.0e-05
  lr_scheduler: false
  lr_scheduler_patience: 30
  max_epochs: 0
  max_samples_query: 1024
  max_samples_support: 8192
  n_classes: 10
  n_ensembles: 1  # FIXME: RENAME: n_estimators
  n_features: 100
  n_heads: 4
  n_layers: 12
  optimizer: adamw
  use_feature_count_scaling: true
  use_quantile_transformer: true
  weight_decay: 0
  y_as_float_embedding: true
