name: "Setup Env Vars"

runs:
  using: "composite"
  steps:
    - name: Get Commit SHA(For push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      env:
        SHA: ${{ github.sha }}
        branch: ${{ github.ref }}
        git_repo: ${{ github.repository }}
        pr_number: ""
      run: |
        
        short_sha=$(git rev-parse --short "$SHA")
        echo "BRANCH=$branch" >> $GITHUB_ENV
        echo "GIT_REPO=$git_repo" >> $GITHUB_ENV
        echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV
        echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
    - name: Get Commit SHA(For pull request)
      if: ${{ github.event_name == 'pull_request_target' }}
      shell: bash
      env:
        SHA: ${{ github.event.pull_request.head.sha }}
        branch: ${{ github.event.pull_request.head.ref }}
        git_repo: ${{ github.event.pull_request.head.repo.full_name }}
        pr_number: PR-${{ github.event.number }}
      run: |
        short_sha=$(git rev-parse --short "$SHA")
        echo "BRANCH=$branch" >> $GITHUB_ENV
        echo "GIT_REPO=$git_repo" >> $GITHUB_ENV
        echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV
        echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
