name: "Setup Env Vars"

runs:
  using: "composite"
  steps:
    - name: Get Commit SHA(For push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        SHA='${{ github.sha }}'
        branch='${{ github.ref }}'
        title="${{ github.event.pull_request.title }}"
        git_repo='${{ github.repository }}'
        short_sha=$(git rev-parse --short "$SHA")
        pr_number="" 

        echo "BRANCH=$branch" >> $GITHUB_ENV
        echo "GIT_REPO=$git_repo" >> $GITHUB_ENV
        echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV
        echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
        echo "TITLE=$title" >> $GITHUB_ENV
    - name: Get Commit SHA(For pull request)
      if: ${{ github.event_name == 'pull_request_target' }}
      shell: bash
      run: |
        branch='${{ github.event.pull_request.head.ref }}'
        title="${{ github.event.pull_request.title }}"
        
        echo "BRANCH=$branch" >> $GITHUB_ENV
        echo "TITLE=$title" >> $GITHUB_ENV
