model:
  names: "hf_text"
  hf_text:
    checkpoint_name: "google/electra-base-discriminator"
    data_types:
      - "text"
    tokenizer_name: "hf_auto"
    merge: True  # Whether we will merge different text columns or treat them independently.
    max_text_len: 512  # The maximum possible length.
    insert_sep: True
    text_segment_num: 2
    stochastic_chunk: False
