name: autogluon_py3
dependencies:
- libpng
- pip
- pip:
  - ipykernel>=4.5.1,<6.0.0
  - jupyter-sphinx>=0.2.2
  - mxnet==1.7.0.post2
  - portalocker
  - scipy>=1.3.3,<1.6.0
  - nose
  - docutils
  - mu-notedown
  - flake8
  - awscli>=1.18.140
