
BINARY = 'binary'
MULTICLASS = 'multiclass'
REGRESSION = 'regression'
LANGUAGE_MODEL = 'language_model'

PROBLEM_TYPES_CLASSIFICATION = [BINARY, MULTICLASS]
PROBLEM_TYPES_REGRESSION = [REGRESSION]
PROBLEM_TYPES = PROBLEM_TYPES_CLASSIFICATION + PROBLEM_TYPES_REGRESSION
