name: autogluon_py3
dependencies:
- python=3.7
- graphviz
- pip:
  - --find-links https://sxjscience.github.io/KDD2020/
  - jupyter-sphinx>=0.2.2
  - gluonnlp==0.8.1
  - mxnet_cu101>=1.7.0b20200713, <2.0.0
  - portalocker
  - nose
  - docutils
  - mu-notedown
  - flake8
  - torch
  - neotime
