dependencies:
- python=3.10
- pip
- pip:
  - flake8
  - black~=23.0
  - isort>=5.10
  - sphinx
  - furo
  - myst_parser
  - myst-nb
  - sphinx-material
  - sphinx-togglebutton
  - sphinx-copybutton
  - sphinx-design
  - sphinx-inline-tabs
  - sphinxcontrib-googleanalytics
