name: autogluon_py3
dependencies:
- python=3.7
- graphviz
- pip:
  - jupyter-sphinx>=0.2.2
  - mxnet_cu101==1.7.0
  - portalocker
  - nose
  - docutils
  - mu-notedown
  - flake8
  - awscli>=1.18.140
