dependencies:
  - python=3.8
  - pip
  - pip:
    - sphinx
    - myst_parser
    - sphinx-material
    - furo
    - git+https://github.com/executablebooks/sphinx-togglebutton # because of https://github.com/executablebooks/sphinx-togglebutton/issues/44
    - sphinx-copybutton
    - myst-nb
    - sphinx-design
