name: Run CodeGuru Reviewer

# Checkout PR code with pull_request_target in Actions can be risky because the workflow has access to credential info
# of this repo. For this Action these is no risk because the Action doesn't execute any code or script form the PR.
on: [ push, pull_request_target, workflow_dispatch ]

permissions:
  id-token: write
  contents: read
  security-events: write 

jobs:
  RunCodeGuru:
    name: Run CodeGuru Reviewer CLI in CICD
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        continue-on-error: true
        id: iam-role
        with:
          role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
          aws-region: us-west-2

      - name: Checkout repository
        if: steps.iam-role.outcome == 'success' && ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0         
      - name: Checkout repository(Pull Request Target)
        if: steps.iam-role.outcome == 'success' &&  ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0 
          
      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        if: steps.iam-role.outcome == 'success'
        continue-on-error: false
        with:          
          s3_bucket: codeguru-reviewer-build-artifacts-048169001733-us-west-2

      - name: Upload review result
        if: steps.iam-role.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json
